import{S as L,a as S,i as n}from"./assets/vendor-DWXSRYDZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const d=document.querySelector(".gallery"),w=new L(".gallery a"),m=document.querySelector(".loader"),f=document.querySelector(".js-load-more");function h(o){const e=o.map(({webformatURL:i,largeImageURL:l,tags:t,likes:r,views:s,comments:y,downloads:b})=>`
        <li class="gallery-item">
        <a href="${l}">
        <img src="${i}" alt="${t}" title="${t}"/>
        <div class="info">
<p><b>💖 likes </b>${r} </p>
<p><b>👁️ views </b> ${s}</p>
<p><b>💬 comments </b>${y} </p>
<p><b>⬇️ downloads </b>${b} </p>
        </div>
        </a>
        </li>`).join("");console.log(e),d.insertAdjacentHTML("beforeend",e),w.refresh()}function v(){d.innerHTML=""}function q(){m.classList.add("is-visible")}function $(){m.classList.remove("is-visible")}function M(){f.classList.add("load-more-hiden")}function g(){f.classList.remove("load-more-hiden")}async function p(o,e=1){const{data:i}=await S.get("https://pixabay.com/api/",{params:{page:e,per_page:15,key:"50835299-cfd675820214f48c95352b76b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}});return i}const E=document.querySelector(".form"),O=document.querySelector('[name="search-text"]');document.querySelector(".gallery");document.querySelector(".loader");const P=document.querySelector(".js-load-more");let u=1,c="",a=0;E.addEventListener("submit",R);P.addEventListener("click",x);function R(o){if(o.preventDefault(),c=O.value.trim().toLowerCase(),u=1,a=0,!c){n.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}v(),q(),p(c,u).then(e=>{if(e.hits.length===0){n.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits),a+=e.hits.length,a>=e.totalHits?g():M()}).catch(e=>{n.error({title:"Error",message:`Something went wrong: ${e.message}`,position:"topRight"})}).finally(()=>{$()})}async function x(){u+=1;try{const o=await p(c,u);console.log(o),h(o.hits);const e=document.querySelector(".gallery-item");if(e){const{height:i}=e.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}a+=o.hits.length,a>=o.totalHits&&(g(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){n.error({title:"Error",message:`Something went wrong: ${o.message}`,position:"topRight"})}}
//# sourceMappingURL=index.js.map
